version: '3.7'

volumes:
  double-take_data:
  deepstack_data:
  trainder_db:
  trainder_uploads:
services:
  double-take:
    container_name: double-take
    image: jakowenko/double-take
    restart: unless-stopped
    volumes:
      - double-take_data:/.storage
    ports:
      - target: 3000
        published: 3000
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  deepstack:
    container_name: deepstack
    restart: unless-stopped
    image: deepquestai/deepstack
    ports:
      - '5000:5000'
    environment:
      - VISION-DETECTION=True
      - MODE=High
      - VISION-SCENE=True
      - VISION-FACE=True
    volumes:
      - deepstack_data:/modelstore/detection
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  deepstack_ui:
    container_name: deepstack_ui
    restart: unless-stopped
    image: robmarkcole/deepstack-ui:latest
    environment: 
      - DEEPSTACK_IP=tasks.deepstack
      - DEEPSTACK_PORT=5000
      - DEEPSTACK_TIMEOUT=20
      - DEEPSTACK_UI_DEBUG_MODE=True
    ports:

      - target: 8501
        published: 8501
        mode: host    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  deepstack_trainer:
    image: techblog/deepstack-trainer
    container_name: deepstack_trainer
    privileged: true
    restart: always
    environment:
      - DEEPSTACK_HOST_ADDRESS=tasks.deepstack
      - MIN_CONFIDANCE=0.75
    ports:
      - target: 8080
        published: 8502
        mode: host  
    volumes:
      - trainder_db:/opt/trainer/db #Database storing the uploaded photos data (Filename, Person name, Date).
      - trainder_uploads:/opt/trainer/photos/uploads #Phisical path for storing the images
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]