version: '3.7'

volumes:
  double-take_data:
  deepstack_data:

services:
  double-take:
    container_name: double-take
    image: jakowenko/double-take
    restart: unless-stopped
    volumes:
      - double-take_data:/.storage
    links:
      - deepstack:deepstack
    ports:
      - target: 3000
        published: 3000
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  deepstack:
    container_name: deepstack
    restart: unless-stopped
    image: deepquestai/deepstack
    ports:
      - '5000:5000'
    environment:
      - VISION-DETECTION=True
      - API-KEY=""
    volumes:
      - deepstack_data:/modelstore/detection
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  deepstack_ui:
    container_name: deepstack_ui
    restart: unless-stopped
    image: robmarkcole/deepstack-ui:latest
    links:
      - deepstack:deepstack
    environment: 
      - DEEPSTACK_IP=double-take_deepstack
      - DEEPSTACK_PORT=5000
      - DEEPSTACK_API_KEY=""
      - DEEPSTACK_TIMEOUT=20
      - DEEPSTACK_CUSTOM_MODEL=fire
      - DEEPSTACK_UI_DEBUG_MODE=True
    ports:

      - target: 8501
        published: 8501
        mode: host    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
